version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'game'
      MYSQL_USER: 'game'
      MYSQL_PASSWORD: 'game3'
      MYSQL_ROOT_PASSWORD: 'game3'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: